server:
  port: 8081
  # 云存储配置
  servlet:
    context-path: /free-fs-test
spring:
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
fs:
  files-server:
    type: minio
    local:
      uploadPath: F:\Soft\JAVA\nginx\nginx-1.12.2\static  #windows
      ngxinxUrl: http://localhost
    minio:
      accessKey: minioadmin
      secretKey: minioadmin
      consoleUrl: http://192.168.1.82:9000/
      apiPort: 9000
      defaultBucket: huoyan
    #oss配置
    oss:
      accessKey: oss
      secretKey: oss
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /
knife4j:
  # true:启用knife4j增强模式, false:不启用knife4j增强模式
  enable: true
  #是否开启生产环境保护策略,生产环境下禁止访问接口文档系统,生产环境设置为true,开发环境设置为false,
  production: false
  #对Knife4j提供的资源提供BasicHttp校验,保护文档;production配置为true时,basic认证功能不可用
