server:
  port: 8081
  # 云存储配置
  servlet:
    context-path: /free-fs-test
fs:
  files-server:
    type: local
    local:
      uploadPath: F:\Soft\JAVA\nginx\nginx-1.12.2\static  #windows
      ngxinxUrl: http://localhost
    minio:
      accessKey: minio
      secretKey: minio
    #oss配置
    oss:
      accessKey: oss
      secretKey: oss
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /