server:
  port: 8081
  # 云存储配置
  servlet:
    context-path: /free-fs-test
fs:
  files-server:
    type: oss
    local:
      uploadPath: local
      ngxinxUrl: local
    minio:
      accessKey: minio
      secretKey: minio
    #oss配置
    oss:
      accessKey: oss
      secretKey: oss
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /