server:
  port: 8081
  # 云存储配置
fs:
  files-server:
    type: minio
    local:
      uploadPath: local
      ngxinxUrl: local
    minio:
      accessKey: minio
      secretKey: minio
    #oss配置
    oss:
      accessKey: oss
      secretKey: oss
