GET http://localhost:8080/hello

###
POST http://localhost:8080/hello/post
Content-Type: application/x-www-form-urlencoded

name=TEST

###

POST http://192.168.170.135:3000/create_face_model
Content-Type:multipart/form-data


###

POST http://127.0.0.1:8081/file/addFolder
Content-Type:multipart/form-data

####

POST http://127.0.0.1:8081/file/addFolder
Content-Type: application/x-www-form-urlencoded

####

POST http://127.0.0.1:8081/file/deleteByIds
Content-Type: application/x-www-form-urlencoded

####

POST http://127.0.0.1:8081/file/deleteFile
Content-Type: application/x-www-form-urlencoded

####

POST http://127.0.0.1:8081/file/move
Content-Type: application/x-www-form-urlencoded

####

POST http://127.0.0.1:8081/file/updateByName
Content-Type: application/x-www-form-urlencoded

####

GET http://127.0.0.1:8081/file/downLoad

####

POST http://127.0.0.1:8081/file/upload
####

POST http://127.0.0.1:8081/file/addFolder
Content-Type: application/json

{
  "dirIds":"/43",
  "name":"c1"
}



